# Configurations
excluded:
  - Sources/SharedModels/APODMock.swift
  - Sources/Utilities/StoppingPhaseAnimator.swift
nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10
identifier_name:
  excluded:
    - db
    - id
function_body_length: 70
